### ISSUE TITLE
Failing tests on debian-sid

### ISSUE THREAD

**Issue by mnencia** [kislyuk/argcomplete#199]
I'm upgrading Debian package to version 1.8.1, but the test suite fails with the following errors both with python2 and python3:

```
======================================================================
ERROR: test_file_completion (test.test.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-argcomplete-1.8.1/test/test.py", line 258, in test_file_completion
    os.makedirs(os.path.join("abcdefж", "klm"))
  File "/usr/lib/python2.7/os.py", line 148, in makedirs
    if head and tail and not path.exists(head):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0436' in position 6: ordinal not in range(128)

======================================================================
ERROR: test_filescompleter_filetype_integration (test.test.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-argcomplete-1.8.1/test/test.py", line 273, in test_filescompleter_filetype_integration
    os.makedirs(os.path.join("abcdefж", "klm"))
  File "/usr/lib/python2.7/os.py", line 148, in makedirs
    if head and tail and not path.exists(head):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0436' in position 6: ordinal not in range(128)

======================================================================
ERROR: test_non_ascii (test.test.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-argcomplete-1.8.1/test/test.py", line 379, in test_non_ascii
    self.assertEqual(set(self.run_completer(make_parser(), cmd)),
  File "/build/python-argcomplete-1.8.1/test/test.py", line 364, in make_parser
    parser.add_argument(_str("--книга"), choices=[
  File "/build/python-argcomplete-1.8.1/argcomplete/compat.py", line 18, in ensure_bytes
    x = x.encode(encoding)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 2-6: ordinal not in range(128)
```

At the moment I've disabled these tests, but I'd like to understand why they fails and fix it.

Here the list of installed packages on the build chroot:

```
Installed-Build-Depends:
 autoconf (= 2.69-10),
 automake (= 1:1.15-5),
 autopoint (= 0.19.8.1-1),
 autotools-dev (= 20161112.1),
 base-files (= 9.8),
 base-passwd (= 3.5.43),
 bash (= 4.4-3),
 binutils (= 2.27.90.20170118-1),
 bsdmainutils (= 9.0.12),
 bsdutils (= 1:2.29.1-1),
 build-essential (= 12.2),
 bzip2 (= 1.0.6-8+b1),
 coreutils (= 8.26-2),
 cpp (= 4:6.3.0-1),
 cpp-5 (= 5.4.1-4),
 cpp-6 (= 6.3.0-4),
 dash (= 0.5.8-2.3),
 debconf (= 1.5.60),
 debhelper (= 10.2.3),
 debianutils (= 4.8.1),
 dh-autoreconf (= 13),
 dh-python (= 2.20160818),
 dh-strip-nondeterminism (= 0.029-2),
 diffutils (= 1:3.5-3),
 dpkg (= 1.18.18),
 dpkg-dev (= 1.18.18),
 e2fslibs (= 1.43.3-1),
 e2fsprogs (= 1.43.3-1),
 file (= 1:5.29-2),
 findutils (= 4.6.0+git+20161106-1),
 g++ (= 4:6.3.0-1),
 g++-6 (= 6.3.0-4),
 gcc (= 4:6.3.0-1),
 gcc-5 (= 5.4.1-4),
 gcc-5-base (= 5.4.1-4),
 gcc-6 (= 6.3.0-4),
 gcc-6-base (= 6.3.0-4),
 gettext (= 0.19.8.1-1),
 gettext-base (= 0.19.8.1-1),
 grep (= 2.27-1),
 groff-base (= 1.22.3-9),
 gzip (= 1.6-5),
 hostname (= 3.18),
 init-system-helpers (= 1.47),
 intltool-debian (= 0.35.0+20060710.4),
 libacl1 (= 2.2.52-3),
 libarchive-zip-perl (= 1.59-1),
 libasan2 (= 5.4.1-4),
 libasan3 (= 6.3.0-4),
 libatomic1 (= 6.3.0-4),
 libattr1 (= 1:2.4.47-2),
 libaudit-common (= 1:2.6.7-1),
 libaudit1 (= 1:2.6.7-1),
 libblkid1 (= 2.29.1-1),
 libbsd0 (= 0.8.3-1),
 libbz2-1.0 (= 1.0.6-8+b1),
 libc-bin (= 2.24-9),
 libc-dev-bin (= 2.24-9),
 libc6 (= 2.24-9),
 libc6-dev (= 2.24-9),
 libcap-ng0 (= 0.7.7-3),
 libcc1-0 (= 6.3.0-4),
 libcilkrts5 (= 6.3.0-4),
 libcomerr2 (= 1.43.3-1),
 libcroco3 (= 0.6.11-2),
 libdb5.3 (= 5.3.28-12),
 libdebconfclient0 (= 0.220),
 libdpkg-perl (= 1.18.18),
 libexpat1 (= 2.2.0-2),
 libfdisk1 (= 2.29.1-1),
 libffi6 (= 3.2.1-6),
 libfile-stripnondeterminism-perl (= 0.029-2),
 libgcc-5-dev (= 5.4.1-4),
 libgcc-6-dev (= 6.3.0-4),
 libgcc1 (= 1:6.3.0-4),
 libgcrypt20 (= 1.7.5-3),
 libgdbm3 (= 1.8.3-14),
 libglib2.0-0 (= 2.50.2-2),
 libgmp10 (= 2:6.1.2+dfsg-1),
 libgomp1 (= 6.3.0-4),
 libgpg-error0 (= 1.26-2),
 libicu57 (= 57.1-5),
 libisl15 (= 0.18-1),
 libitm1 (= 6.3.0-4),
 libjs-jquery (= 3.1.1-2),
 libjs-sphinxdoc (= 1.4.9-2),
 libjs-underscore (= 1.8.3~dfsg-1),
 liblsan0 (= 6.3.0-4),
 liblz4-1 (= 0.0~r131-2),
 liblzma5 (= 5.2.2-1.2),
 libmagic-mgc (= 1:5.29-2),
 libmagic1 (= 1:5.29-2),
 libmount1 (= 2.29.1-1),
 libmpc3 (= 1.0.3-1),
 libmpdec2 (= 2.4.2-1),
 libmpfr4 (= 3.1.5-1),
 libmpx0 (= 5.4.1-4),
 libmpx2 (= 6.3.0-4),
 libncurses5 (= 6.0+20161126-1),
 libncursesw5 (= 6.0+20161126-1),
 libpam-modules (= 1.1.8-3.5),
 libpam-modules-bin (= 1.1.8-3.5),
 libpam-runtime (= 1.1.8-3.5),
 libpam0g (= 1.1.8-3.5),
 libpcre3 (= 2:8.39-2),
 libperl5.24 (= 5.24.1-1),
 libpipeline1 (= 1.4.1-2),
 libpython-stdlib (= 2.7.13-1),
 libpython2.7-minimal (= 2.7.13-2),
 libpython2.7-stdlib (= 2.7.13-2),
 libpython3-stdlib (= 3.5.3-1),
 libpython3.5-minimal (= 3.5.3-1),
 libpython3.5-stdlib (= 3.5.3-1),
 libquadmath0 (= 6.3.0-4),
 libreadline7 (= 7.0-1),
 libselinux1 (= 2.6-3),
 libsemanage-common (= 2.6-2),
 libsemanage1 (= 2.6-2),
 libsepol1 (= 2.6-2),
 libsigsegv2 (= 2.10-5),
 libsmartcols1 (= 2.29.1-1),
 libsqlite3-0 (= 3.16.2-1),
 libss2 (= 1.43.3-1),
 libssl1.1 (= 1.1.0c-4),
 libstdc++-6-dev (= 6.3.0-4),
 libstdc++6 (= 6.3.0-4),
 libsystemd0 (= 232-12),
 libtimedate-perl (= 2.3000-2),
 libtinfo5 (= 6.0+20161126-1),
 libtool (= 2.4.6-2),
 libtsan0 (= 6.3.0-4),
 libubsan0 (= 6.3.0-4),
 libudev1 (= 232-12),
 libunistring0 (= 0.9.6+really0.9.3-0.1),
 libustr-1.0-1 (= 1.0.4-6),
 libuuid1 (= 2.29.1-1),
 libxml2 (= 2.9.4+dfsg1-2.1),
 linux-libc-dev (= 4.9.2-2),
 login (= 1:4.4-2),
 m4 (= 1.4.18-1),
 make (= 4.1-9),
 man-db (= 2.7.6.1-2),
 mawk (= 1.3.3-17),
 mime-support (= 3.60),
 mount (= 2.29.1-1),
 ncurses-base (= 6.0+20161126-1),
 ncurses-bin (= 6.0+20161126-1),
 passwd (= 1:4.4-2),
 patch (= 2.7.5-1),
 perl (= 5.24.1-1),
 perl-base (= 5.24.1-1),
 perl-modules-5.24 (= 5.24.1-1),
 po-debconf (= 1.0.20),
 python (= 2.7.13-1),
 python-all (= 2.7.13-1),
 python-configparser (= 3.3.0r2-2),
 python-coverage (= 4.2+dfsg.1-2),
 python-enum34 (= 1.1.6-1),
 python-flake8 (= 3.2.1-1),
 python-mccabe (= 0.5.2-2),
 python-pexpect (= 4.2.1-1),
 python-pkg-resources (= 33.1.1-1),
 python-ptyprocess (= 0.5.1-1),
 python-pycodestyle (= 2.2.0-2),
 python-pyflakes (= 1.3.0-1),
 python-setuptools (= 33.1.1-1),
 python-wheel (= 0.29.0-2),
 python2.7 (= 2.7.13-2),
 python2.7-minimal (= 2.7.13-2),
 python3 (= 3.5.3-1),
 python3-all (= 3.5.3-1),
 python3-coverage (= 4.2+dfsg.1-2),
 python3-flake8 (= 3.2.1-1),
 python3-mccabe (= 0.5.2-2),
 python3-pexpect (= 4.2.1-1),
 python3-pkg-resources (= 33.1.1-1),
 python3-ptyprocess (= 0.5.1-1),
 python3-pycodestyle (= 2.2.0-2),
 python3-pyflakes (= 1.3.0-1),
 python3-setuptools (= 33.1.1-1),
 python3-wheel (= 0.29.0-2),
 python3.5 (= 3.5.3-1),
 python3.5-minimal (= 3.5.3-1),
 readline-common (= 7.0-1),
 sed (= 4.3-3),
 sensible-utils (= 0.0.9),
 sysvinit-utils (= 2.88dsf-59.8),
 tar (= 1.29b-1.1),
 tcsh (= 6.20.00-4),
 util-linux (= 2.29.1-1),
 xz-utils (= 5.2.2-1.2),
 zlib1g (= 1:1.2.8.dfsg-4)
```

**Comment by evanunderscore** [comment]
These look the same as the first few failures in #174. What is the output of `locale` on your machine?

**Comment by mnencia** [comment]
I did some tests and i found that the build environment is set to have `LOCALE=C` and `LC_ALL=C`. Once I've unset LC_ALL at the beginning of the build script, the tests have started working as expected.  Is it expected?

**Comment by evanunderscore** [comment]
Yes, argcomplete uses the locale setting to encode and decode strings (as does Python itself in some cases). We could potentially try to patch the locale in the tests to work around a bad testing environment, or perhaps just display a useful error in the test suite when we know these tests are going to fail.

**Comment by mnencia** [comment]
What about using something like:

@unittest.skipIf(os.environ.get('LC_ALL') and 'UTF-8' not in os.environ.['LC_ALL'], "not supported with a non UTF-8 language in LC_ALL")

**Comment by kislyuk** [comment]
I'm not sure what that is intended to accomplish. If your build environment is not i18n compliant, and the package tests for i18n compliance and fails, that sounds like something the build environment should accommodate, not the package.

**Comment by mnencia** [comment]
Well, at the moment I don't have anything to accomplish :-) I've fixed the build script and that's enough to build an updated Debian packages. 

My last suggestion was aim to help casual testers to understand what is happening, but probably it was in the wrong direction. 

I think that the right thing to do is to add some comment to these tests pointing to this ticket or to  #174 in order to easily discover why these tests can fail and how to fix the testing environment.

**Comment by kislyuk** [comment]
Closing because there is nothing to do on the package side.
