### ISSUE TITLE
Not work with unicode as input

### ISSUE THREAD

**Issue by cuyu** [kislyuk/argcomplete#228]
Example code as below:
```python
def MyCompleter(prefix, **kwargs):
    results = ['aaa', 'bbb']
    return (c for c in results if c.startswith(prefix))

if __name__ == '__main__':
    import argparse
    import argcomplete

    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest='command')
    create_parser = subparsers.add_parser('new')
    create_parser.add_argument('title')
    create_parser.add_argument('category').completer = MyCompleter
    argcomplete.autocomplete(parser)
    args = parser.parse_args()
    print args
```

It works as expect when all the inputs are normal characters (assume above code are wrapped in command `demo`):
```bash
$ ./demo.py new 'hi'
--help  -h      aaa     bbb  
```
When the input contains unicode, the auto completer is not working:
```bash
$ ./demo.py new '你好'
```

So, is this a bug or something related to the shell?
I'm using zsh and argcomplete (Version: 1.9.2).

**Comment by evanunderscore** [comment]
It looks like zsh is being smarter than bash and giving COMP_POINT in unicode chars instead of bytes. When we incorrectly interpret that number, we end up slicing the input halfway through a character, which we then fail to decode. Even if that didn't crash, the results would likely be undesirable.

I used bashcompinit as described [here](https://github.com/kislyuk/argcomplete/issues/10#issuecomment-19369876) to reproduce this. I'm assuming bashcompinit is supposed to emulate bash completion, in which case I'd say this should be considered a bug on their end.

On the other hand, [the documentation for COMP_POINT](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#Bash-Variables) explicitly says "If the current cursor position is at the end of the current command, the value of this variable is equal to ${#COMP_LINE}." So bashcompinit is adhering to the spec and bash is not.

**Comment by cuyu** [comment]
@evanunderscore Thanks for your quick response.

From my understanding, the problem should only occur on zsh according to your explanation.
However, I just tested on a bash environment, the problem still exists. Can you have a look at this issue on a bash env again?

Thanks!

**Comment by evanunderscore** [comment]
I did test in bash previously and it worked for me. Can you `export _ARC_DEBUG=1`, try again, and tell me if you see a traceback?

**Comment by cuyu** [comment]
Enabled `export _ARC_DEBUG=1` and got the following errors:
```
$ /home/demo.py '的' word word  split (lexer stopped, state: ' ')
Traceback (most recent call last):
  File "/home/demo.py", line 17, in <module>
    argcomplete.autocomplete(parser)
  File "/usr/local/lib/python2.7/dist-packages/argcomplete/__init__.py", line 216, in __call__
    "\nWORDS:", comp_words)
  File "/usr/local/lib/python2.7/dist-packages/argcomplete/__init__.py", line 18, in debug
    print(file=debug_stream, *args)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u7684' in position 30: ordinal not in range(128)
word word  split (lexer stopped, state: ' ')
Traceback (most recent call last):
  File "/home/splunk/demo.py", line 17, in <module>
    argcomplete.autocomplete(parser)
  File "/usr/local/lib/python2.7/dist-packages/argcomplete/__init__.py", line 216, in __call__
    "\nWORDS:", comp_words)
  File "/usr/local/lib/python2.7/dist-packages/argcomplete/__init__.py", line 18, in debug
    print(file=debug_stream, *args)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u7684' in position 30: ordinal not in range(128)
```

**Comment by cuyu** [comment]
Above errors are just caused in debugging functions. After fixing the EncodeError, I can get the following traceback:
```
$ /home/demo.py new 你好 word word  split (lexer stopped, state: ' ')

LINE: '/home/demo.py new 你好 '
PREQUOTE: ''
PREFIX: ''
SUFFIX: ''
WORDS: [u'/home/demo.py', u'new']
Active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
Visited positionals: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
invoking parser with ['new']
Action stub called on IntrospectAction(option_strings=[], dest='command', nargs='A...', const=None, default=None, type=None, choices=OrderedDict([('new', ArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True))]), help=None, metavar=None)
	args: MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True) Namespace(command=None) ['new'] None
	orig class: <class 'argparse._SubParsersAction'>
	orig callable: <bound method _SubParsersAction.__call__ of IntrospectAction(option_strings=[], dest='command', nargs='A...', const=None, default=None, type=None, choices=OrderedDict([('new', ArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True))]), help=None, metavar=None)>
orig class is a subparsers action: patching and running it

exception <type 'exceptions.SystemExit'> 2 while parsing args
all active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
active_parser: MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
optional options: [u'-h', u'--help']
next_positional: IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
Active actions (L=1): [IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)]
Activating completion for IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None) <class 'argparse._StoreAction'>
Completions: [u'-h', u'--help', u'.X0-lock', u'tmpA8NnUR/', u'tmpXTor03/', u'tmph7jZJ4/', u'tmpLrzjc_/', u'tmpG1w0ak/', u'tmp9TIEsP/', u'vmware-root/', u'tmpKjTfie/', u'tmp4lxBp7/', u'_drafts/', u'tmpaltdy_/', u'tmpZbSdbg/', u'.X11-unix/', u'tmpEgiTO0/', u'tmp4bkmG7/', u'tmpvGnhyY/', u'.ICE-unix/', u'_posts/']
active options: [u'-h', u'--help', u'.X0-lock', u'tmpA8NnUR/', u'tmpXTor03/', u'tmph7jZJ4/', u'tmpLrzjc_/', u'tmpG1w0ak/', u'tmp9TIEsP/', u'vmware-root/', u'tmpKjTfie/', u'tmp4lxBp7/', u'_drafts/', u'tmpaltdy_/', u'tmpZbSdbg/', u'.X11-unix/', u'tmpEgiTO0/', u'tmp4bkmG7/', u'tmpvGnhyY/', u'.ICE-unix/', u'_posts/']
display completions: {u'tmph7jZJ4/': u'', u'tmp9TIEsP/': u'', u'tmpZbSdbg/': u'', u'.X0-lock': u'', u'tmpKjTfie/': u'', u'tmpvGnhyY/': u'', u'_posts/': u'', u'tmpaltdy_/': u'', u'tmpA8NnUR/': u'', u'.X11-unix/': u'', u'_drafts/': u'', u'-h --help': 'show this help message and exit', u'tmpEgiTO0/': u'', u'tmp4lxBp7/': u'', u'tmpXTor03/': u'', u'tmp4bkmG7/': u'', u'.ICE-unix/': u'', u'tmpLrzjc_/': u'', u'vmware-root/': u'', u'tmpG1w0ak/': u''}

Returning completions: [u'-h', u'--help', u'.X0-lock', u'tmpA8NnUR/', u'tmpXTor03/', u'tmph7jZJ4/', u'tmpLrzjc_/', u'tmpG1w0ak/', u'tmp9TIEsP/', u'vmware-root/', u'tmpKjTfie/', u'tmp4lxBp7/', u'_drafts/', u'tmpaltdy_/', u'tmpZbSdbg/', u'.X11-unix/', u'tmpEgiTO0/', u'tmp4bkmG7/', u'tmpvGnhyY/', u'.ICE-unix/', u'_posts/']
```
While for non-unicode inputs, the traceback is like:
```
$ /home/demo.py new hi word hi split, lexer state: ' '
In trailing whitespace

LINE: '/home/demo.py new hi '
PREQUOTE: ''
PREFIX: ''
SUFFIX: ''
WORDS: [u'/home/demo.py', u'new', u'hi']
Active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
Visited positionals: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
invoking parser with ['new', 'hi']
Action stub called on IntrospectAction(option_strings=[], dest='command', nargs='A...', const=None, default=None, type=None, choices=OrderedDict([('new', ArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True))]), help=None, metavar=None)
	args: MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True) Namespace(command=None) ['new', 'hi'] None
	orig class: <class 'argparse._SubParsersAction'>
	orig callable: <bound method _SubParsersAction.__call__ of IntrospectAction(option_strings=[], dest='command', nargs='A...', const=None, default=None, type=None, choices=OrderedDict([('new', ArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True))]), help=None, metavar=None)>
orig class is a subparsers action: patching and running it
Action stub called on IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
	args: MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True) Namespace(category=None, command='new', title=None) hi None
	orig class: <class 'argparse._StoreAction'>
	orig callable: <bound method _StoreAction.__call__ of IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)>

exception <type 'exceptions.SystemExit'> 2 while parsing args
all active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
active_parser: MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
optional options: [u'-h', u'--help']
next_positional: IntrospectAction(option_strings=[], dest='category', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
Active actions (L=2): [IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None), IntrospectAction(option_strings=[], dest='category', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)]
Skipping IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
Activating completion for IntrospectAction(option_strings=[], dest='category', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None) <class 'argparse._StoreAction'>
Completions: [u'-h', u'--help', 'aaa', 'bbb']
active options: [u'-h', u'--help', 'aaa', 'bbb']
display completions: {u'-h --help': 'show this help message and exit', 'aaa': u'', 'bbb': u''}

Returning completions: [u'-h', u'--help', u'aaa', u'bbb']
```

It looks like the unicode word is not counted when parsing the inputs.

**Comment by cuyu** [comment]
Strangely, this problem cannot reproduce on my mac.
For above tracebacks, I tested based on the following env:
```bash
$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.1 LTS"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.1 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
$ python --version
Python 2.7.6
$ echo $BASH_VERSION
4.3.11(1)-release
```
Maybe this is a bug of bash or something else.
Anyway, @evanunderscore thanks for the responses. It really helps.

**Comment by evanunderscore** [comment]
When you say you "fixed the encoding errors" above, what did you actually do? I'm not able to get unicode to print to the debug stream in Python 2 because the debug stream expects to be writing bytes. When I fix that, I end up with the output I expected.

**Comment by evanunderscore** [comment]
I've created #230 to deal with the debug stream issues. Can you please work off that branch and tell me if you get different output to what you posted above?

**Comment by cuyu** [comment]
Using the fixed debug stream code of https://github.com/kislyuk/argcomplete/pull/230, I can get the following debug info in a bash env:
```
# ./demo.py new 嘚瑟
word 嘚瑟 split, lexer state: ' '

LINE: './demo.py new 嘚瑟 '
PREQUOTE: ''
PREFIX: '嘚'
SUFFIX: '瑟'
WORDS: [u'./demo.py', u'new']
Active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
Visited positionals: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
invoking parser with ['new']
Action stub called on IntrospectAction(option_strings=[], dest='command', nargs='A...', const=None, default=None, type=None, choices=OrderedDict([('new', ArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True))]), help=None, metavar=None)
	args: MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True) Namespace(command=None) ['new'] None
	orig class: <class 'argparse._SubParsersAction'>
	orig callable: <bound method _SubParsersAction.__call__ of IntrospectAction(option_strings=[], dest='command', nargs='A...', const=None, default=None, type=None, choices=OrderedDict([('new', ArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True))]), help=None, metavar=None)>
orig class is a subparsers action: patching and running it

exception <type 'exceptions.SystemExit'> 2 while parsing args
all active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True), MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
active_parser: MonkeyPatchedIntrospectiveArgumentParser(prog='demo.py new', usage=None, description=None, version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
optional options: []
next_positional: IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)
Active actions (L=1): [IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None)]
Activating completion for IntrospectAction(option_strings=[], dest='title', nargs=None, const=None, default=None, type=None, choices=None, help=None, metavar=None) <class 'argparse._StoreAction'>
Completions: []
active options: []
display completions: {u'': 'show this help message and exit'}

Returning completions: []
```
And the following inputs caused crash:
```
# ./demo.py new 你好嘚瑟
Traceback (most recent call last):
  File "./demo.py", line 17, in <module>
    argcomplete.autocomplete(parser)
  File "/usr/local/lib/python2.7/dist-packages/argcomplete/__init__.py", line 204, in __call__
    comp_point = len(comp_line[:comp_point].decode(sys_encoding))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 17-18: unexpected end of data
```
I think the splitting of the inputs is not correct and the correct splitting should use the `comp_point` before the following transform:
```python
        # Adjust comp_point for wide chars
        if USING_PYTHON2:
            comp_point = len(comp_line[:comp_point].decode(sys_encoding))
        else:
            comp_point = len(comp_line.encode(sys_encoding)[:comp_point].decode(sys_encoding))
```

And from my testing, **if there is a space before the cursor**, the difference between bash and zsh is that the COMP_POINT come from zsh equals the COMP_POINT+1 from bash. If there is no space before the cursor, the COMP_POINT is calculated differently between zsh and bash (as @evanunderscore explains above).
For example (replcae the `[space]` with actual space key):

shell | Input( cursor at the end of the input) | COMP_POINT
-- | -- | --
bash | `./demo.py new 你好嘚瑟` | 18
bash | `./demo.py new 你好嘚瑟[space]` | 19
zsh | `./demo.py new 你好嘚瑟` | 23
zsh | `./demo.py new 你好嘚瑟[space]` | 20

Point out to me if anything is not right in this comment. Thanks.

**Comment by evanunderscore** [comment]
Thanks for the detailed information @cuyu. I'll take a look when I get some spare time, although that might not be for a little while.

**Comment by evanunderscore** [comment]
Thanks for your patience @cuyu. I've just come back and had a look at this.

I can reproduce the same results as you're showing in your table, which means my previous assessment was incorrect - bash is adhering to its documentation (in that `${#COMP_LINE}` agrees with the two values of `COMP_POINT` in your table), and zsh misses the mark in both cases. I also don't think zsh is counting unicode characters, since the length of COMP_LINE in bytes in those cases should be 26 and 27 respectively. This looks like a bug in bashcompinit.

The good news is this means the code to adjust COMP_POINT is actually not necessary at all - I have removed it and written some extra test cases, and everything looks fine. The incorrect values of COMP_LINE in zsh will only impact completion if you try to complete from somewhere other than the end of the line, which is not so bad. The original test case you reported was likely only failing due to argcomplete being unable to write to the debug stream, even though it would never have been displayed.

@cuyu Would you like to report this bug to the maintainers of bashcompinit?

**Comment by evanunderscore** [comment]
This was closed automatically because I linked it to the PR, but I'd like to keep it open as a reminder until the bashcompinit bug has been reported.

**Comment by cuyu** [comment]
Hi @evanunderscore, I would like to report this bug but I cannot find the entry of issue reporting for bashcompinit.. Please report (you can use my examples) if you know where to go.

**Comment by evanunderscore** [comment]
@cuyu I have emailed the zsh mailing list with details of the problem and a proposed fix. I will report back with the resolution. If you wish to alter your own installation of zsh to fix the problem, you need to change line 11 of bashcompinit from this:
```
(( COMP_POINT = 1 + ${#${(j. .)words[1,CURRENT]}} + $#QIPREFIX + $#IPREFIX + $#PREFIX ))
```
to this:
```
(( COMP_POINT = 1 + ${#${(j. .)words[1,CURRENT-1]}} + $#QIPREFIX + $#IPREFIX + $#PREFIX ))
```
Note that this problem has nothing to do with unicode characters.

**Comment by cuyu** [comment]
@evanunderscore That's cool! Will try the fix.

**Comment by evanunderscore** [comment]
The fix is now in zsh's master branch (https://github.com/zsh-users/zsh/commit/e2f793e7df7214cc3d80e2fcfe961ed087c860ab).
