### ISSUE TITLE
few tests are failing

### ISSUE THREAD

**Issue by ignatenkobrain** [kislyuk/argcomplete#256]
```python
======================================================================
FAIL: test_python_completion (test.test.TestBashGlobal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/argcomplete-1.9.4/test/test.py", line 1144, in test_python_completion
    self.assertEqual(self.sh.run_command('/usr/bin/python3 ./prog basic f\t'), 'foo\r\n')
AssertionError: "usage: prog basic [-h] {foo,bar,baz}\r\n[86 chars]\r\n" != 'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')


======================================================================
FAIL: test_python_filename_completion (test.test.TestBashGlobal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/argcomplete-1.9.4/test/test.py", line 1148, in test_python_filename_completion
    self.assertEqual(self.sh.run_command('/usr/bin/python3 ./pro\tbasic f\t'), 'foo\r\n')
AssertionError: "usage: prog basic [-h] {foo,bar,baz}\r\n[86 chars]\r\n" != 'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')


======================================================================
FAIL: test_python_module (test.test.TestBashGlobal)
Test completing a module run with /usr/bin/python3 -m.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/argcomplete-1.9.4/test/test.py", line 1170, in test_python_module
    self.assertEqual(self.sh.run_command('/usr/bin/python3 -m package.prog basic f\t'), 'foo\r\n')
AssertionError: "usage: prog.py basic [-h] {foo,bar,baz}\[92 chars]\r\n" != 'foo\r\n'
+ foo
- usage: prog.py basic [-h] {foo,bar,baz}
- prog.py basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')


======================================================================
FAIL: test_python_not_executable (test.test.TestBashGlobal)
Test completing a script that cannot be run directly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/argcomplete-1.9.4/test/test.py", line 1160, in test_python_not_executable
    self.assertEqual(self.sh.run_command('/usr/bin/python3 ./prog basic f\t'), 'foo\r\n')
AssertionError: "usage: prog basic [-h] {foo,bar,baz}\r\n[86 chars]\r\n" != 'foo\r\n'
+ foo
- usage: prog basic [-h] {foo,bar,baz}
- prog basic: error: argument arg: invalid choice: 'f' (choose from 'foo', 'bar', 'baz')
```

**Comment by kislyuk** [comment]
This is most likely because your Bash version is out of date.

**Comment by ignatenkobrain** [comment]
bash-4.4.23-3.fc29.x86_64
bash-completion-2.8-2.fc29.noarch

**Comment by kislyuk** [comment]
That is up to date.

Thanks, will take a look.

**Comment by evanunderscore** [comment]
Those lines all use `/usr/bin/python3`, which test.py currently does not - are you working off a branch, or did you alter the file yourself as a result of some problem you encountered in #255? As I mentioned there, these tests will not work with `/usr/bin/python*`.

We can talk about how we want global completion to work, but in the meantime I recommend using a virtual environment with the version of Python you want to test against, so that `python` is pointing to the right interpreter.

**Comment by ignatenkobrain** [comment]
We can't use virtualenvs, because this is package in Fedora. So we have to use system-wide packages. Which effectively means that we can't make python point to python3 (that's against one of PEPs). And we want to remove python2 from the distribution.

**Comment by evanunderscore** [comment]
Since the test failures are only related to changes you made for #255, I'm going to close this and any remaining discussion can go there.
