### ISSUE TITLE
test/test_package missing from pypi tarball

### ISSUE THREAD

**Issue by mgorny** [kislyuk/argcomplete#273]
The `test/test_package` directory is not included in the 1.10.1 tarball which causes the tests to fail:

```
======================================================================
FAIL: test_console_script_module (__main__.TestBashGlobal)
Test completing a console_script for a module.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 1206, in test_console_script_module
    self._test_console_script()
  File "test/test.py", line 1197, in _test_console_script
    self.assertEqual(self.sh.run_command('echo $?'), '0\r\n', install_output)
AssertionError: [33mDEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support[0m
[31mERROR: Invalid requirement: '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package'
Hint: It looks like a path. File '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package' does not exist.[0m


======================================================================
FAIL: test_console_script_module_wheel (__main__.TestBashGlobal)
Test completing a console_script for a module from a wheel.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 1214, in test_console_script_module_wheel
    self._test_console_script(wheel=True)
  File "test/test.py", line 1197, in _test_console_script
    self.assertEqual(self.sh.run_command('echo $?'), '0\r\n', install_output)
AssertionError: [33mDEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support[0m
[31mERROR: Invalid requirement: '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package'
Hint: It looks like a path. File '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package' does not exist.[0m


======================================================================
FAIL: test_console_script_package (__main__.TestBashGlobal)
Test completing a console_script for a package.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 1210, in test_console_script_package
    self._test_console_script(package=True)
  File "test/test.py", line 1197, in _test_console_script
    self.assertEqual(self.sh.run_command('echo $?'), '0\r\n', install_output)
AssertionError: [33mDEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support[0m
[31mERROR: Invalid requirement: '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package'
Hint: It looks like a path. File '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package' does not exist.[0m


======================================================================
FAIL: test_console_script_package_wheel (__main__.TestBashGlobal)
Test completing a console_script for a package from a wheel.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 1218, in test_console_script_package_wheel
    self._test_console_script(package=True, wheel=True)
  File "test/test.py", line 1197, in _test_console_script
    self.assertEqual(self.sh.run_command('echo $?'), '0\r\n', install_output)
AssertionError: [33mDEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support[0m
[31mERROR: Invalid requirement: '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package'
Hint: It looks like a path. File '/tmp/portage/dev-python/argcomplete-1.10.1/work/argcomplete-1.10.1/test/test_package' does not exist.[0m

**Comment by kislyuk** [comment]
Fixed in v1.10.2, thanks.
