### ISSUE TITLE
1 Error and 13 failed tests with Python 3.12.7

### ISSUE THREAD

**Issue by mcepl** [kislyuk/argcomplete#507]
With the upgrade to 3.12.7 tests started to fail, most likely because of [large changes to argparse module](https://docs.python.org/3/whatsnew/changelog.html#changelog):

```
[  246s] ======================================================================
[  246s] ERROR: test_repl_parse_after_complete (__main__.TestArgcompleteREPL.test_repl_parse_after_complete)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 934, in test_repl_parse_after_complete
[  246s]     args = p.parse_args(["--foo", "spam", "bar"])
[  246s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  246s]   File "/usr/lib64/python3.12/argparse.py", line 1895, in parse_args
[  246s]     args, argv = self.parse_known_args(args, namespace)
[  246s]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  246s]   File "/usr/lib64/python3.12/argparse.py", line 1931, in parse_known_args
[  246s]     namespace, args = self._parse_known_args(args, namespace)
[  246s]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/argcomplete/packages/_argparse.py", line 302, in _parse_known_args
[  246s]     start_index = consume_optional(start_index)
[  246s]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/argcomplete/packages/_argparse.py", line 168, in consume_optional
[  246s]     action, option_string, _, explicit_arg = option_tuple
[  246s]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  246s] ValueError: not enough values to unpack (expected 4, got 1)
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_choices (__main__.TestArgcomplete.test_choices)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 179, in test_choices
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--help'
[  246s] '-h'
[  246s] '--ship'
[  246s] Items in the second set but not the first:
[  246s] 'submarine'
[  246s] 'speedboat'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_completers (__main__.TestArgcomplete.test_completers)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 300, in test_completers
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--help'
[  246s] '-h'
[  246s] '--url'
[  246s] '--email'
[  246s] Items in the second set but not the first:
[  246s] 'http://url1'
[  246s] 'http://url2'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_default_completer (__main__.TestArgcomplete.test_default_completer)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 424, in test_default_completer
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--many'
[  246s] '--one'
[  246s] Items in the second set but not the first:
[  246s] 'test/'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_escape_special_chars (__main__.TestArgcomplete.test_escape_special_chars)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 832, in test_escape_special_chars
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), "prog -1 ")), {r"bar\<\$\>baz "})
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '-2'
[  246s] '-1'
[  246s] '-3'
[  246s] Items in the second set but not the first:
[  246s] 'bar\\<\\$\\>baz '
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_exclusive (__main__.TestArgcomplete.test_exclusive)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 773, in test_exclusive
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--no-bar'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_exclusive_class (__main__.TestArgcomplete.test_exclusive_class)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 822, in test_exclusive_class
[  246s]     self.assertEqual(set(self.run_completer(parser, cmd, completer=completer)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--no-bar'
[  246s] '--foo'
[  246s] '--bar'
[  246s] '--baz'
[  246s] Items in the second set but not the first:
[  246s] 'baz2'
[  246s] 'baz1'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_filescompleter_filetype_integration (__main__.TestArgcomplete.test_filescompleter_filetype_integration)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 378, in test_filescompleter_filetype_integration
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--help'
[  246s] '-h'
[  246s] '--r'
[  246s] '--w'
[  246s] Items in the second set but not the first:
[  246s] 'abcdefж/'
[  246s] 'abcaha/'
[  246s] 'abcxyz'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_mixed_optional_positional (__main__.TestArgcomplete.test_mixed_optional_positional)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 793, in test_mixed_optional_positional
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--set'
[  246s] Items in the second set but not the first:
[  246s] 'name1'
[  246s] 'name2'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_non_ascii (__main__.TestArgcomplete.test_non_ascii)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 482, in test_non_ascii
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--help'
[  246s] '-h'
[  246s] '--книга'
[  246s] Items in the second set but not the first:
[  246s] 'Понедельник\\ начинается\\ в\\ субботу'
[  246s] 'Трудно\\ быть\\ богом'
[  246s] 'Парень\\ из\\ преисподней'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_optional_nargs (__main__.TestArgcomplete.test_optional_nargs)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 697, in test_optional_nargs
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] '--help'
[  246s] '--bar'
[  246s] '--foo'
[  246s] '--foobar'
[  246s] '-h'
[  246s] '--baz'
[  246s] '--qux'
[  246s] Items in the second set but not the first:
[  246s] 'foo1'
[  246s] 'foo2'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_positional_remainder (__main__.TestArgcomplete.test_positional_remainder)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 717, in test_positional_remainder
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the second set but not the first:
[  246s] 'pos'
[  246s] '--opt'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_subparser_completers (__main__.TestArgcomplete.test_subparser_completers)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 345, in test_subparser_completers
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the second set but not the first:
[  246s] 'val5'
[  246s] 
[  246s] ======================================================================
[  246s] FAIL: test_subparsers (__main__.TestArgcomplete.test_subparsers)
[  246s] ----------------------------------------------------------------------
[  246s] Traceback (most recent call last):
[  246s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 451, in test_subparsers
[  246s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  246s] AssertionError: Items in the first set but not the second:
[  246s] 'spam'
[  246s] '--age'
[  246s] 'eggs'
[  246s] Items in the second set but not the first:
[  246s] 'on\\ a\\ boat'
[  246s] 'in\\ the\\ rain'
[  246s] 'on\\ a\\ train'
[  246s] 'with\\ a\\ goat'
[  246s] 
[  246s] ----------------------------------------------------------------------
[  246s] Ran 189 tests in 116.052s
[  246s] 
[  246s] FAILED (failures=13, errors=1, skipped=12, expected failures=5)
```

[Complete build log](https://github.com/user-attachments/files/17266582/_log.txt) with all packages used and all steps taken to reproduce.

**Comment by kristopolous** [comment]
I am also getting an effectively 0% pass rate regardless of moving my python version around to different versions.
So I tried 3.10.15, 3.11.10, 3.12.7, on bash and zsh, on multiple machines. Essentially this:

```
$ pyenv global 3.11.10
$ python3 -mvenv env-3.11.10
$ source env-3.11.10/bin/activate
$ make clean
$ make install
$ make test
```
I've included one of the logs [test-3.11.19.txt](https://github.com/user-attachments/files/17528719/test-3.11.19.txt)
 as an example but the results are effectively the same. A screenful of errors and a bunch of failures.

```
$ git describe 
v3.5.1
```

To avoid any possible artifacts contributing to the failure I was also able to replicate this from a fresh account with a fresh home directory. I'm on Ubuntu 24.04.1 LTS


I also tried different tags of the source with the different python versions on the different machines, in different shells, using different users. Nothing works and almost all the tests reliably fail

**Comment by kislyuk** [comment]
This was fixed in the most recent release.

**Comment by mcepl** [comment]
Hmm, I cannot support this claim. With 3.4.0 I get:

```
[  248s] ======================================================================
[  248s] ERROR: test_repl_parse_after_complete (__main__.TestArgcompleteREPL.test_repl_parse_after_complete)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 934, in test_repl_parse_after_complete
[  248s]     args = p.parse_args(["--foo", "spam", "bar"])
[  248s]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  248s]   File "/usr/lib64/python3.12/argparse.py", line 1895, in parse_args
[  248s]     args, argv = self.parse_known_args(args, namespace)
[  248s]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  248s]   File "/usr/lib64/python3.12/argparse.py", line 1931, in parse_known_args
[  248s]     namespace, args = self._parse_known_args(args, namespace)
[  248s]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/argcomplete/packages/_argparse.py", line 302, in _parse_known_args
[  248s]     start_index = consume_optional(start_index)
[  248s]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/argcomplete/packages/_argparse.py", line 168, in consume_optional
[  248s]     action, option_string, _, explicit_arg = option_tuple
[  248s]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[  248s] ValueError: not enough values to unpack (expected 4, got 1)
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_choices (__main__.TestArgcomplete.test_choices)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 179, in test_choices
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--help'
[  248s] '-h'
[  248s] '--ship'
[  248s] Items in the second set but not the first:
[  248s] 'submarine'
[  248s] 'speedboat'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_completers (__main__.TestArgcomplete.test_completers)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 300, in test_completers
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--help'
[  248s] '-h'
[  248s] '--url'
[  248s] '--email'
[  248s] Items in the second set but not the first:
[  248s] 'http://url1'
[  248s] 'http://url2'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_default_completer (__main__.TestArgcomplete.test_default_completer)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 424, in test_default_completer
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--many'
[  248s] '--one'
[  248s] Items in the second set but not the first:
[  248s] 'test/'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_escape_special_chars (__main__.TestArgcomplete.test_escape_special_chars)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 832, in test_escape_special_chars
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), "prog -1 ")), {r"bar\<\$\>baz "})
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '-2'
[  248s] '-1'
[  248s] '-3'
[  248s] Items in the second set but not the first:
[  248s] 'bar\\<\\$\\>baz '
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_exclusive (__main__.TestArgcomplete.test_exclusive)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 773, in test_exclusive
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--no-bar'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_exclusive_class (__main__.TestArgcomplete.test_exclusive_class)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 822, in test_exclusive_class
[  248s]     self.assertEqual(set(self.run_completer(parser, cmd, completer=completer)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--no-bar'
[  248s] '--foo'
[  248s] '--bar'
[  248s] '--baz'
[  248s] Items in the second set but not the first:
[  248s] 'baz2'
[  248s] 'baz1'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_filescompleter_filetype_integration (__main__.TestArgcomplete.test_filescompleter_filetype_integration)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 378, in test_filescompleter_filetype_integration
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--help'
[  248s] '-h'
[  248s] '--r'
[  248s] '--w'
[  248s] Items in the second set but not the first:
[  248s] 'abcdefж/'
[  248s] 'abcaha/'
[  248s] 'abcxyz'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_mixed_optional_positional (__main__.TestArgcomplete.test_mixed_optional_positional)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 793, in test_mixed_optional_positional
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--set'
[  248s] Items in the second set but not the first:
[  248s] 'name1'
[  248s] 'name2'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_non_ascii (__main__.TestArgcomplete.test_non_ascii)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 482, in test_non_ascii
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--help'
[  248s] '-h'
[  248s] '--книга'
[  248s] Items in the second set but not the first:
[  248s] 'Понедельник\\ начинается\\ в\\ субботу'
[  248s] 'Трудно\\ быть\\ богом'
[  248s] 'Парень\\ из\\ преисподней'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_optional_nargs (__main__.TestArgcomplete.test_optional_nargs)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 697, in test_optional_nargs
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] '--help'
[  248s] '--bar'
[  248s] '--foo'
[  248s] '--foobar'
[  248s] '-h'
[  248s] '--baz'
[  248s] '--qux'
[  248s] Items in the second set but not the first:
[  248s] 'foo1'
[  248s] 'foo2'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_positional_remainder (__main__.TestArgcomplete.test_positional_remainder)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 717, in test_positional_remainder
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the second set but not the first:
[  248s] 'pos'
[  248s] '--opt'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_subparser_completers (__main__.TestArgcomplete.test_subparser_completers)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 345, in test_subparser_completers
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the second set but not the first:
[  248s] 'val5'
[  248s] 
[  248s] ======================================================================
[  248s] FAIL: test_subparsers (__main__.TestArgcomplete.test_subparsers)
[  248s] ----------------------------------------------------------------------
[  248s] Traceback (most recent call last):
[  248s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.4.0/./test/test.py", line 451, in test_subparsers
[  248s]     self.assertEqual(set(self.run_completer(make_parser(), cmd)), set(output))
[  248s] AssertionError: Items in the first set but not the second:
[  248s] 'spam'
[  248s] '--age'
[  248s] 'eggs'
[  248s] Items in the second set but not the first:
[  248s] 'on\\ a\\ boat'
[  248s] 'in\\ the\\ rain'
[  248s] 'on\\ a\\ train'
[  248s] 'with\\ a\\ goat'
[  248s] 
[  248s] ----------------------------------------------------------------------
[  248s] Ran 189 tests in 115.884s
[  248s] 
[  248s] FAILED (failures=13, errors=1, skipped=12, expected failures=5)
```

[Complete build log](https://github.com/user-attachments/files/17535070/_log.txt)

**Comment by kislyuk** [comment]
@mcepl sorry, it was late at night and I pasted the wrong version. The latest release, v3.5.1, is what I meant.

**Comment by mcepl** [comment]
I don’t know, it seems like the situation is even worse. Zillion tests fail with this error:

```
[   67s] ======================================================================
[   67s] FAIL: test_single_quoted_completion (__main__.TestZshGlobalExplicit)
[   67s] ----------------------------------------------------------------------
[   67s] Traceback (most recent call last):
[   67s]   File "/home/abuild/rpmbuild/BUILD/argcomplete-3.5.1/./test/test.py", line 1271, in setUp
[   67s]     self.assertEqual(output, "")
[   67s] AssertionError: 'zsh: command not found: activate-global-python-argcomplete\r\n' != ''
[   67s] - zsh: command not found: activate-global-python-argcomplete
```
[Complete build log](https://github.com/user-attachments/files/17549053/_log.txt)

**Comment by kislyuk** [comment]
@mcepl that looks like a different issue, not related to the argparse changes in Python 3.12.7.

In v3.5.0, argcomplete changed the way entry point scripts are installed (https://github.com/kislyuk/argcomplete/pull/498). Your build environment seems like it might not be compatible with the new way the scripts are installed.

**Comment by mcepl** [comment]
Right, I had to split building and testing into two separate steps, because testing is not possible against only partially installed package. https://build.opensuse.org/request/show/1219176 Thank you for the hint!
