### ISSUE TITLE
Files/Directory Completers throw an exception

### ISSUE THREAD

**Issue by dhylands** [kislyuk/argcomplete#518]
Python Version: 3.10.12
argcomplete version: 3.5.2
shell: bash
Running on ubuntu 22.04

Sample program:
```
#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
import argparse
import argcomplete

from argcomplete.completers import FilesCompleter, DirectoriesCompleter

parser = argparse.ArgumentParser()
parser.add_argument("--progress", action='store_true', help="Show progress")
parser.add_argument("--xfile", help="Name of file to download").completer = FilesCompleter
parser.add_argument("--ydir", help="Directory to put it in").completer = DirectoriesCompleter
parser.add_argument("file", help="Name of file to download").completer = FilesCompleter
parser.add_argument("dir", help="Directory to put it in").completer = DirectoriesCompleter

argcomplete.autocomplete(parser)
args = parser.parse_args()

print(f'progress: {args.progress}')
print(f'   xfile: {args.xfile}')
print(f'    ydir: {args.ydir}')
print(f'    file: {args.file}')
print(f'     dir: {args.dir}')
```

If I do `export _ARC_DEBUG=1` and I type `./pgm.py --xfile <TAB>` I get the following output:
```
2068 >./pgm.py --xfile 
word --xfile split, lexer state: ' '
In trailing whitespace

LINE: './pgm.py --xfile ' 
POINT: 17 
PREQUOTE: '' 
PREFIX: '' 
SUFFIX: '' 
WORDS: ['./pgm.py', '--xfile']
Active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='pgm.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
Visited positionals: [MonkeyPatchedIntrospectiveArgumentParser(prog='pgm.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
invoking parser with ['--xfile']

exception <class 'SystemExit'> 2 while parsing args
all active parsers: [MonkeyPatchedIntrospectiveArgumentParser(prog='pgm.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)]
active_parser: MonkeyPatchedIntrospectiveArgumentParser(prog='pgm.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
optional options: ['-h', '--help', '--progress', '--xfile', '--ydir']
next_positional: IntrospectAction(option_strings=[], dest='file', nargs=None, const=None, default=None, type=None, choices=None, required=True, help='Name of file to download', metavar=None)
Active actions (L=1): [IntrospectAction(option_strings=['--xfile'], dest='xfile', nargs=None, const=None, default=None, type=None, choices=None, required=False, help='Name of file to download', metavar=None)]
Resetting completions because IntrospectAction(option_strings=['--xfile'], dest='xfile', nargs=None, const=None, default=None, type=None, choices=None, required=False, help='Name of file to download', metavar=None) must consume the next argument
Activating completion for IntrospectAction(option_strings=['--xfile'], dest='xfile', nargs=None, const=None, default=None, type=None, choices=None, required=False, help='Name of file to download', metavar=None) <class 'argparse._StoreAction'>
Traceback (most recent call last):
  File "/home/dhylands/test/argcomplete/./pgm.py", line 15, in <module>
    argcomplete.autocomplete(parser)
  File "/home/dhylands/test/argcomplete/.direnv/python-3.10.12/lib/python3.10/site-packages/argcomplete/finders.py", line 174, in __call__
    completions = self._get_completions(comp_words, cword_prefix, cword_prequote, last_wordbreak_pos)
  File "/home/dhylands/test/argcomplete/.direnv/python-3.10.12/lib/python3.10/site-packages/argcomplete/finders.py", line 223, in _get_completions
    completions = self.collect_completions(active_parsers, parsed_args, cword_prefix)
  File "/home/dhylands/test/argcomplete/.direnv/python-3.10.12/lib/python3.10/site-packages/argcomplete/finders.py", line 449, in collect_completions
    completions = self._complete_active_option(
  File "/home/dhylands/test/argcomplete/.direnv/python-3.10.12/lib/python3.10/site-packages/argcomplete/finders.py", line 395, in _complete_active_option
    completer_output = completer(
TypeError: FilesCompleter.__init__() got an unexpected keyword argument 'prefix'
argcomplete.txt 
```

I get the same error when using DirectoriesCompleter.

**Comment by kislyuk** [comment]
The completer attribute should be set to an _instance_ of the FilesCompleter/DirectoriesCompleter class:
```
parser.add_argument("--xfile", help="Name of file to download").completer = FilesCompleter()
```
Please try that and let us know if you have any further issues. I'll see if we can make the documentation clearer.
